version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/lebedev
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/lebedev
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - mysql
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - APP_ENV=${APP_ENV}

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/lebedev
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli

  mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql:delegated
    container_name: mysql
    # restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql: